name: soundtry
description: نظام إدارة المخزون والصيانة
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Database
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # File Operations
  file_picker: ^6.1.1
  
  # PDF & Printing
  pdf: ^3.10.7
  printing: ^5.12.0
  
  # Utilities
  intl: ^0.20.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # إضافة الأصول
  assets:
    - assets/barcode.jpg

  
  # fonts:
  #   - family: Arial
  #     fonts:
  #       - asset: fonts/arial.ttf